version: "3"

networks:
  treinamento_net:
    driver: bridge

volumes:
  postgres_data:

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres data:/var/lib/postgresql/data
    networks:
      - treinamento_net

  dbeaver:
    image: dbeaver/cloudbeaver:24.0.4
    ports:
      - "8080:8978"
    networks:
      - treinamento_net
    depends_on:
      - db
